Debugging - pause on each compilation step

diff --git a/packages/compilation-tools/packaging b/packages/compilation-tools/packaging
--- a/packages/compilation-tools/packaging
+++ b/packages/compilation-tools/packaging
@@ -1,5 +1,5 @@
-set -e # exit immediately if a simple command exits with a non-zero status
-#set -u # report the usage of uninitialized variables
+#set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
 # $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
@@ -71,4 +71,10 @@ do
   cd $ext_dir
   make prefix=$BOSH_INSTALL_TARGET && make install
   cd ..
+done
+
+touch /tmp/continue
+while [ -f /tmp/continue ]
+do
+  sleep 240
 done
diff --git a/packages/gcc/packaging b/packages/gcc/packaging
--- a/packages/gcc/packaging
+++ b/packages/gcc/packaging
@@ -1,4 +1,4 @@
-set -e # exit immediately if a simple command exits with a non-zero status
+#set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -172,4 +172,10 @@ do
   ./configure --prefix=$BOSH_INSTALL_TARGET CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib
   make && make install
   cd ..
+done
+
+touch /tmp/continue
+while [ -f /tmp/continue ]
+do
+  sleep 240
 done
diff --git a/packages/mongodb/packaging b/packages/mongodb/packaging
--- a/packages/mongodb/packaging
+++ b/packages/mongodb/packaging
@@ -1,5 +1,5 @@
-set -e # exit immediately if a simple command exits with a non-zero status
-#set -u # report the usage of uninitialized variables
+#set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
 # $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
@@ -193,4 +193,10 @@ do
   [ ! -d $BOSH_INSTALL_TARGET/bin ] && mkdir -p $BOSH_INSTALL_TARGET/bin
   cp -rp bin/* $BOSH_INSTALL_TARGET/bin
   cd ..
+done
+
+touch /tmp/continue
+while [ -f /tmp/continue ]
+do
+  sleep 240
 done
