Removing sleep

diff --git a/packages/binutils/packaging b/packages/binutils/packaging
--- a/packages/binutils/packaging
+++ b/packages/binutils/packaging
@@ -1,4 +1,4 @@
-#set -e # exit immediately if a simple command exits with a non-zero status
+set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -73,8 +73,3 @@ do
   make install
 done
 
-touch /tmp/continue
-while [ -f /tmp/continue ]
-do
-  sleep 240
-done
diff --git a/packages/compilation-tools/packaging b/packages/compilation-tools/packaging
--- a/packages/compilation-tools/packaging
+++ b/packages/compilation-tools/packaging
@@ -1,4 +1,4 @@
-#set -e # exit immediately if a simple command exits with a non-zero status
+set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -69,12 +69,6 @@ do
   ext_dir=`tar -tvf $i |tail -1|tr -s [:space:]| cut -d" " -f6 |cut -d"/" -f1`
   tar xf $i
   cd $ext_dir
-  make prefix=$BOSH_INSTALL_TARGET && make install
+  make prefix=$BOSH_INSTALL_TARGET && make prefix=$BOSH_INSTALL_TARGET install
   cd ..
-done
-
-touch /tmp/continue
-while [ -f /tmp/continue ]
-do
-  sleep 240
 done
diff --git a/packages/compressors/packaging b/packages/compressors/packaging
--- a/packages/compressors/packaging
+++ b/packages/compressors/packaging
@@ -1,4 +1,4 @@
-#set -e # exit immediately if a simple command exits with a non-zero status
+set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -80,10 +80,4 @@ do
   LDFLAGS="-L/var/vcap/packages/gcc/lib  -L/var/vcap/packages/gcc/lib64" make
   PREFIX=$BOSH_INSTALL_TARGET make install 
   cd ..
-done
-
-touch /tmp/continue
-while [ -f /tmp/continue ]
-do
-  sleep 240
 done
diff --git a/packages/gcc/packaging b/packages/gcc/packaging
--- a/packages/gcc/packaging
+++ b/packages/gcc/packaging
@@ -1,4 +1,4 @@
-#set -e # exit immediately if a simple command exits with a non-zero status
+set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -31,7 +31,7 @@ do
   ext_dir=`tar -tvf $i |tail -1| tr -s [:space:] | cut -d" " -f6 |cut -d"/" -f1`
   tar xf $i
   cd $ext_dir
-  ./configure --prefix=$BOSH_INSTALL_TARGET M4=$BOSH_INSTALL_TARGET/bin/m4
+   M4=$BOSH_INSTALL_TARGET/bin/m4 ./configure --prefix=$BOSH_INSTALL_TARGET 
   make && make install
   cd ..
 done
@@ -112,7 +112,7 @@ do
   cd $ext_dir
   mkdir build
   cd build
-  ../configure --prefix=$BOSH_INSTALL_TARGET CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib
+  CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib ../configure --prefix=$BOSH_INSTALL_TARGET 
   make && make install
   cd ../..
 done
@@ -125,7 +125,7 @@ do
   cd $ext_dir
   mkdir build
   cd build
-  ../configure --prefix=$BOSH_INSTALL_TARGET CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib
+  CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib ../configure --prefix=$BOSH_INSTALL_TARGET 
   make && make install
   cd ../..
 done  
@@ -138,7 +138,7 @@ do
   cd $ext_dir
   mkdir build
   cd build
-  ../configure --prefix=$BOSH_INSTALL_TARGET CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib
+  CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib ../configure --prefix=$BOSH_INSTALL_TARGET 
   make && make install
   cd ../..
 done
@@ -169,13 +169,7 @@ do
   perl -pe 's#^AM_CFLAGS = .*#AM_CFLAGS = -g#' -i Makefile.in
   perl -pe 's#^includesdir = .*#includesdir = \@includedir\@#' -i include/Makefile.in
 
-  ./configure --prefix=$BOSH_INSTALL_TARGET CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib
+  CC=$BOSH_INSTALL_TARGET/bin/gcc CPPFLAGS=-I$BOSH_INSTALL_TARGET/include LDFLAGS=-L$BOSH_INSTALL_TARGET/lib ./configure --prefix=$BOSH_INSTALL_TARGET 
   make && make install
   cd ..
-done
-
-touch /tmp/continue
-while [ -f /tmp/continue ]
-do
-  sleep 240
 done
diff --git a/packages/openssl/packaging b/packages/openssl/packaging
--- a/packages/openssl/packaging
+++ b/packages/openssl/packaging
@@ -1,4 +1,4 @@
-#set -e # exit immediately if a simple command exits with a non-zero status
+set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -25,10 +25,4 @@ do
   RANLIB=/var/vcap/packages/binutils/bin/ranlib ./Configure -fPIC shared --prefix=$BOSH_INSTALL_TARGET linux-x86_64 -I/var/vcap/packages/gcc/include -L/var/vcap/packages/gcc/lib -L/var/vcap/packages/gcc/lib64 
   make -j $cpun_
   make install
-done
-
-touch /tmp/continue
-while [ -f /tmp/continue ]
-do
-  sleep 240
 done
diff --git a/packages/scons/packaging b/packages/scons/packaging
--- a/packages/scons/packaging
+++ b/packages/scons/packaging
@@ -1,4 +1,4 @@
-#set -e # exit immediately if a simple command exits with a non-zero status
+set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -17,10 +17,4 @@ do
   tar xf $i
   cd $ext_dir
   /var/vcap/packages/python/bin/python setup.py install --prefix=$BOSH_INSTALL_TARGET 
-done
-
-touch /tmp/continue
-while [ -f /tmp/continue ]
-do
-  sleep 240
 done
