Correct openssl libaries and include path

diff --git a/packages/mongodb/packaging b/packages/mongodb/packaging
--- a/packages/mongodb/packaging
+++ b/packages/mongodb/packaging
@@ -1,4 +1,4 @@
-set -e # exit immediately if a simple command exits with a non-zero status
+# set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -16,12 +16,12 @@ do
 done
 
 export C_INCLUDE_PATH=${C_INCLUDE_PATH:-''}
-for package_inc_dir in $(ls -d /var/vcap/packages/*/include)
+for package_inc_dir in $(ls -d /var/vcap/packages/*/include /var/vcap/packages/*/include/*/ )
 do
   export C_INCLUDE_PATH=${package_inc_dir}:$C_INCLUDE_PATH
 done
 
-export PATH=/var/vcap/packages/gcc/bin:/var/vcap/packages/binutils/bin:/var/vcap/packages/python/bin/:/var/vcap/packages/scons/bin:$PATH
+export PATH=/var/vcap/packages/gcc/bin:/var/vcap/packages/binutils/bin:/var/vcap/packages/python/bin/:/var/vcap/packages/scons/bin:/var/vcap/packages/openssl/bin:$PATH
 
 # Retrieving number of cpus on compilation server
 export cpun_=`lscpu | grep '^CPU('|tr -d [:space:]|cut -d":" -f2`
@@ -34,8 +34,8 @@ do
   tar xf $i
   cd $ext_dir
   CC=/var/vcap/packages/gcc/bin/gcc CXX=/var/vcap/packages/gcc/bin/g++ EXTRA_CFLAGS=-fPIC \
-  CFLAGS="-I/var/vcap/packages/compressors/include -I/var/vcap/packages/gcc/include -I/var/vcap/packages/openssl/include" \
-  LDFLAGS="-L/var/vcap/packages/compressors/lib -L/var/vcap/packages/gcc/lib -L/var/vcap/packages/gcc/lib64 -L/var/vcap/packages/openssl/lib -L/var/vcap/packages/openssl/lib64 -lsnappy -llz4 -lzstd" \
+  CFLAGS="-I/var/vcap/packages/compressors/include -I/var/vcap/packages/gcc/include -I/var/vcap/packages/openssl/include/openssl" \
+  LDFLAGS="-L/var/vcap/packages/compressors/lib -L/var/vcap/packages/gcc/lib -L/var/vcap/packages/gcc/lib64 -L/var/vcap/packages/openssl/lib -lsnappy -llz4 -lzstd -lssl -lcrypto" \
   EXTRA_CXXFLAGS=-fPIC DISABLE_JEMALLOC=1 PORTABLE=1 make -j $cpun_ static_lib
   INSTALL_PATH=$BOSH_INSTALL_TARGET make install
   cd ..
@@ -62,10 +62,10 @@ do
 
 export CC="/var/vcap/packages/gcc/bin/gcc" 
 export CXX="/var/vcap/packages/gcc/bin/g++" 
-export CPPPATH="$BOSH_INSTALL_TARGET/include /var/vcap/packages/compressors/include /var/vcap/packages/gcc/include /var/vcap/packages/openssl/include" 
-export LIBPATH="$BOSH_INSTALL_TARGET/lib /var/vcap/packages/compressors/lib /var/vcap/packages/gcc/lib /var/vcap/packages/gcc/lib64 /var/vcap/packages/openssl/lib/*"
-export LDFLAGS="-L/var/vcap/packages/compressors/lib -L/var/vcap/packages/gcc/lib -L/var/vcap/packages/gcc/lib64 -L/var/vcap/packages/openssl/lib -L/var/vcap/packages/openssl/lib64 -lsnappy -llz4 -lzstd"
-export CPPFLAGS="-I/var/vcap/packages/gcc/include -I/var/vcap/packages/compressors/include -I/var/vcap/packages/openssl/include -I$BOSH_INSTALL_TARGET/include"
+export CPPPATH="$BOSH_INSTALL_TARGET/include /var/vcap/packages/compressors/include /var/vcap/packages/gcc/include /var/vcap/packages/openssl/include/openssl" 
+export LIBPATH="$BOSH_INSTALL_TARGET/lib /var/vcap/packages/compressors/lib /var/vcap/packages/gcc/lib /var/vcap/packages/gcc/lib64 /var/vcap/packages/openssl/lib"
+export LDFLAGS="-L/var/vcap/packages/compressors/lib -L/var/vcap/packages/gcc/lib -L/var/vcap/packages/gcc/lib64 -L/var/vcap/packages/openssl/lib -lsnappy -llz4 -lzstd -lssl -lcrypto"
+export CPPFLAGS="-I/var/vcap/packages/gcc/include -I/var/vcap/packages/compressors/include -I/var/vcap/packages/openssl/include/openssl -I$BOSH_INSTALL_TARGET/include"
 export AR="/var/vcap/packages/binutils/bin/ar" 
 export RANLIB="/var/vcap/packages/binutils/bin/ranlib" 
 export LD="/var/vcap/packages/binutils/bin/ld" # not working ?
@@ -124,10 +124,11 @@ do
   cd $ext_dir
   # need libpcap for mongoreplay
   source /var/vcap/packages/golang-1.8-linux/bosh/compile.env
-  export CGO_LDFLAGS="-L/var/vcap/packages/gcc/lib -L/var/vcap/packages/gcc/lib64"
+  export CGO_LDFLAGS="-L/var/vcap/packages/gcc/lib -L/var/vcap/packages/gcc/lib64 -L/var/vcap/packages/openssl/lib"
   ./set_gopath.sh
   ./build.sh
   [ ! -d $BOSH_INSTALL_TARGET/bin ] && mkdir -p $BOSH_INSTALL_TARGET/bin
   cp -rp bin/* $BOSH_INSTALL_TARGET/bin
   cd ..
 done
+
