bzip.org is no more available which cause compressors to not be compiled

diff --git a/packages/mongodb/packaging b/packages/mongodb/packaging
--- a/packages/mongodb/packaging
+++ b/packages/mongodb/packaging
@@ -1,4 +1,4 @@
-#set -e # exit immediately if a simple command exits with a non-zero status
+set -e # exit immediately if a simple command exits with a non-zero status
 #set -u # report the usage of uninitialized variables
 
 # $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
@@ -113,6 +113,7 @@ do
            -L/var/vcap/packages/gcc/lib \
            -L/var/vcap/packages/gcc/lib64 \
            -L/var/vcap/packages/openssl/lib \
+           -L $BOSH_INSTALL_TARGET/lib \
            -lsnappy -llz4 -lzstd -lssl -lcrypto"
   export LIBS="lz4 zstd snappy ssl crypto"
   export CPPFLAGS="-I/var/vcap/packages/gcc/include \
@@ -161,12 +162,6 @@ env['LINKFLAGS'] += SCons.Util.CLVar(os.environ['LDFLAGS'])\n" SConstruct
   MONGO_VERSION=$_mongo_version \
   core install
 
-  touch /tmp/continue
-  while [ -f /tmp/continue ]
-  do
-    sleep 6000
-  done
-
   # striping binaries
   # mongo 3.6 introduce python script install_compass which should not be stripped
   file /var/vcap/packages/mongodb/bin/* \
@@ -192,4 +187,8 @@ do
   cd ..
 done
 
-
+touch /tmp/continue
+while [ -f /tmp/continue ]
+do
+  sleep 120
+done
